### ISSUE TITLE
Supabase Db file ?

### ISSUE THREAD

**Issue by rohitsangwan01** [shanuflash/invoicezz#2]
Hey nice project, can you please share Supabase Db schema ?

**Comment by shanuflash** [comment]
I'll share it once am home

**Comment by shanuflash** [comment]
> Hey nice project, can you please share Supabase Db schema ?

<img width="633" alt="Screenshot 2023-09-05 at 11 44 30 PM" src="https://github.com/shanuflash/invoicezz/assets/39374797/b5df845a-8d89-4be5-bd94-f91bbef0cd03">
<img width="637" alt="Screenshot 2023-09-05 at 11 45 38 PM" src="https://github.com/shanuflash/invoicezz/assets/39374797/8cdd151f-f16b-4526-9d16-189e75c26f44">
<img width="641" alt="Screenshot 2023-09-05 at 11 45 59 PM" src="https://github.com/shanuflash/invoicezz/assets/39374797/bab9a09b-5c5c-4a9c-a6d4-bb8674a661fc">
